### ISSUE TITLE
Is this repo maintained?

### ISSUE THREAD

**Issue by noam-honig** [zation/vite-plugin-express#1]
Hi, 

I tried running this code  and got errors from vite regarding `require`

So, I've written my version of it at: https://github.com/noam-honig/vite3-plugin-express

If you do not plan to maintain this repo, would you be willing to remove the npm package - so I can name mine as `vite-plugin-express`

Let me know.

**Comment by zation** [comment]
If you got any error and want to fix it, a PR or example is welcome.
If you want to make a better plugin, please at least provide the same features including:
* glob path
* hot reload when add a new file in the glob config
